name: Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: daniyalmaster693
          output: dist/snake.svg
      - name: Commit and Push Snake
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate Snake Animation"
          file_pattern: dist/snake.svg
